branch-defaults:
  default:
    environment: null
    group_suffix: null
  master:
    environment: udagram-dev
    group_suffix: null
global:
  application_name: udagram
  branch: null
  default_ec2_keyname: mykeypair
  default_platform: Node.js 20 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: default
  repository: null
  sc: git
  workspace_type: Application
